### ISSUE TITLE
Swipe Action

### ISSUE THREAD

**Issue by manojrana97** [mac-gallagher/Shuffle#84] opened 2020-06-22 12:44 UTC
If we want to just show the next element on right swipe and previous with a left swipe. Then what will we need to do?

**Comment by mac-gallagher** [comment] 2020-06-23 00:07
This sounds like a duplicate of #59 

TLDR: this library is probably not appropriate if you aren't planning on disposing cards after swiping

**Closed by mac-gallagher** 2020-06-23 00:07 UTC
Labels: enhancement
