### ISSUE TITLE
Only the ImageView for the last card in the array shows but all other info is displayed correctly

### ISSUE THREAD

**Issue by timmyvc123** [mac-gallagher/Shuffle#127] opened 2021-03-05 19:59 UTC
Hey I'm trying to integrate the Spotify API into the shuffle library by fetching the song name, artist name, and music artwork  and displaying it on the cards. For some reason it only shows the artwork for the last card in the array but shows the correct song name and artist name for all the other cards.

```swift
func fetchAndConfigureSearch() {
        
        let randomOffset = Int.random(in: 0..<1000)
        
        let token = (UserDefaults.standard.string(forKey: "token"))
        
        api.call(request: .search(token: token!, q: getRandomSearch(), type: .track, market: "US", limit: 5, offset: randomOffset) { [self] result in
            
            let tracks = result as? Result<SearchTracks, Error>
            
            switch tracks {
            
            case .success(let something):
                
                for track in something.tracks.items {
                    
                    let newTrack = SimpleTrack(artistName: track.album.artists.first?.name,
                                               id: track.id,
                                               title: track.name,
                                               previewURL: track.previewUrl,
                                               images: track.album.images!,
                                               albumName: track.album.name)
                    
                    let coverImageURL = newTrack.images[0].url
                    self.imageView.kf.setImage(with: coverImageURL)
                                        
                    let songModel = CardModel(songName: newTrack.title, artistName: newTrack.artistName, imageView: imageView)
                    cardModels.append(songModel)
                    let newIndices = Array(self.cardModels.count-1..<self.cardModels.count)
                    self.cardStack.appendCards(atIndices: newIndices)
                }
            case .failure(let error):
                print("search query failed bc... ", error)
            case .none:
                print("not decoding correctly")
            }
        })   
    }
```

https://user-images.githubusercontent.com/38578011/110167101-45519000-7dc3-11eb-901b-34dad5ba220e.mp4

**Comment by mac-gallagher** [comment] 2021-03-06 04:23
@timmyvc123  Can you try dispatching `self.cardStack.appendCards(atIndices: newIndices)` to the main thread?

**Comment by timmyvc123** [comment] 2021-03-08 21:58
When I do that I get this error: `Fatal error: Invalid update: invalid number of cards. The number of cards contained in the card stack after the update (5) must be equal to the number of cards contained in the card stack before the update (0), plus or minus the number of cards inserted or deleted (1 inserted, 0 deleted): file Shuffle_iOS/SwipeCardStack.swift, line 388`

When I wrap the whole for loop I get the same issue as my original post

**Comment by mac-gallagher** [comment] 2021-03-08 22:56
The issue is 
```swift
let newIndices = Array(self.cardModels.count-1..<self.cardModels.count)
``` 
will only ever be one index, hence the `1 inserted`. You need to calculate how many cards were added. Look more closely at the `addCards` function in the example here https://github.com/mac-gallagher/Shuffle/blob/master/Documentation/AdvancedUsage.md#inserting-and-deleting-cards

In your particular case, I think this should work
```swift
let oldModelsCount = self.cardModels

/// fetch from api and update self.cardModels

let newModelsCount = oldModelsCount + something.tracks.items.count
let newIndices = Array(oldModelsCount..<newModelsCount)

self.cardStack.appendCards(atIndices: newIndices)
```

**Comment by timmyvc123** [comment] 2021-03-09 00:06
Did you mean `let oldModelsCount = self.cardModels.count` ? Also, still getting the same error with that change

**Comment by mac-gallagher** [comment] 2021-03-09 00:11
Yes - updated my response.

After calling `appendCards(atIndices:)`, the `numberOfCards` method from `SwipeCardStackDataSource` is returning 5 cards. However, you are only providing one new index to `appendCards(atIndices:)`. You must also give 5 new indices to `appendCards(atIndices:)`

**Comment by timmyvc123** [comment] 2021-03-09 03:07
Do you have a suggestion for appending the 5 new indices to `appendCard(atIndices:)` ?

**Comment by mac-gallagher** [comment] 2021-03-09 05:19
Can you share your code with the suggested change that is still not working?

**Comment by timmyvc123** [comment] 2021-03-09 05:33
This is what I'm working with: `  func fetchAndConfigureSearch() {
        
        let oldModelsCount = self.cardModels.count
        
        let randomOffset = Int.random(in: 0..<1000)
        
        let token = (UserDefaults.standard.string(forKey: "token"))
        
        api.call(request: .search(token: token!, q: getRandomSearch(), type: .track, market: "US", limit: 5, offset: randomOffset) { [self] result in
            
            let tracks = result as? Result<SearchTracks, Error>
            
            switch tracks {
            
            case .success(let something):
                
                for track in something.tracks.items {
                    
                    let newTrack = SimpleTrack(artistName: track.album.artists.first?.name,
                                               id: track.id,
                                               title: track.name,
                                               previewURL: track.previewUrl,
                                               images: track.album.images!,
                                               albumName: track.album.name)
                    
                    let coverImageURL = newTrack.images[0].url
                    self.imageView.kf.setImage(with: coverImageURL)
                                        
                    let songModel = CardModel(songName: newTrack.title, artistName: newTrack.artistName, imageView: imageView)
                    cardModels.append(songModel)
                    
                    let newModelsCount = oldModelsCount + something.tracks.items.count
                    let newIndices = Array(oldModelsCount..<newModelsCount)
                    
                    DispatchQueue.main.async {
                        self.cardStack.appendCards(atIndices: newIndices)

                    }
                }
            case .failure(let error):
                print("search query failed bc... ", error)
            case .none:
                print("not decoding correctly")
            }
        })
        
    }
    `
This is the error now: `Fatal error: Invalid update: invalid number of cards. The number of cards contained in the card stack after the update (5) must be equal to the number of cards contained in the card stack before the update (5), plus or minus the number of cards inserted or deleted (5 inserted, 0 deleted): file Shuffle_iOS/SwipeCardStack.swift, line 388`

**Comment by mac-gallagher** [comment] 2021-03-09 05:42
Can you please try what I suggested above? Add your new card models to a local variable `newModels` and then call `appendCards` outside the loop:

```swift
var newModels = [CardModel]()
let oldModelsCount = self.cardModels.count

for track in something.tracks.items {
  let newTrack = SimpleTrack(artistName: track.album.artists.first?.name,
                                                  id: track.id,
                                                  title: track.name,
                                                  previewURL: track.previewUrl,
                                                  images: track.album.images!,
                                                  albumName: track.album.name)
                
  let coverImageURL = newTrack.images[0].url
  self.imageView.kf.setImage(with: coverImageURL)
                                    
  let songModel = CardModel(songName: newTrack.title, artistName: newTrack.artistName, imageView: imageView)
  newModels.append(songModel)
                
  let newIndices = Array(oldModelsCount..< newModels.count)
}                
  
DispatchQueue.main.async {
  self.cardStack.appendCards(atIndices: newIndices)
}
```

**Comment by timmyvc123** [comment] 2021-03-09 05:52
Sorry didn't see that suggestion. No error anymore but still having the original issue where only the picture for last card in the array shows. No getters or setters.

**Comment by mac-gallagher** [comment] 2021-03-09 05:58
@timmyvc123  So upon rewatching the video, it looks like Shuffle is actually doing its job correctly. The cards are displaying the card models properly - it is only the image view which has an issue. I suspect the issue is 
```
let coverImageURL = newTrack.images[0].url
self.imageView.kf.setImage(with: coverImageURL)
```

Are you sure `coverImageURL ` is non-null for each API response? I'm not sure which library this is from, but you might want to try dispatching this to the main thread as well

**Comment by mac-gallagher** [comment] 2021-03-09 06:00
In any case, closing this issue since the problem isn't coming from the Shuffle library

**Closed by mac-gallagher** 2021-03-09 06:00 UTC
Labels: bug

**Comment by timmyvc123** [comment] 2021-03-09 06:03
@mac-gallagher Yeah that's why I was confused because everything else was correct like the artist and song names. I'm using the Spotify API and trying to get the cover photo for each song. When I was loading the images in an image view before implementing shuffle they always showed. So I'm not sure but I'll try to figure it out. Really appreciate the time and help!

**Comment by mac-gallagher** [comment] 2021-03-09 06:05
@timmyvc123 no problem, feel free to re-open if you are convinced there is something wrong with the library. Seems like a tricky issue!

**Comment by timmyvc123** [comment] 2021-03-10 06:24
If anyone runs into this very specific problem using the Spotify API with Shuffle the best solution I found was just loading one song at a time in the request and calling the function in `func didSwipeAllCards(_ cardStack: SwipeCardStack)`

**Comment by mac-gallagher** [comment] 2021-03-17 01:43
@timmyvc123 circling back here. The following line is questionable to me
```swift
self.imageView.kf.setImage(with: coverImageURL)
```
It looks like there is only _one_ image view here. Your `cardForIndexAt` should look something like
```swift
 func cardStack(_ cardStack: SwipeCardStack, cardForIndexAt index: Int) -> SwipeCard {
    let card = SwipeCard()
    let cardModel = self.cardModels[index]
    card.imageView.setImage(cardModel.images[0].url)
    return card
  }
```
i.e., there should be an imageView as a subview *on each card*

**Comment by timmyvc123** [comment] 2021-03-17 01:56
This is the code I have `cardForIndexAt` currently

```Swift
 func cardStack(_ cardStack: SwipeCardStack, cardForIndexAt index: Int) -> SwipeCard {
        let card = SwipeCard()
         let model = cardModels[index]
        card.content = CardContentView(withImageView: model.imageView)
        card.footer = CardFooterView(withTitle: "\(model.songName)", subtitle: model.artistName)
        return card
```

**Comment by mac-gallagher** [comment] 2021-03-17 01:58
@timmyvc123 what is the reason for passing the imageView to `CardContentView` instead of just the image?

**Comment by mac-gallagher** [comment] 2021-03-17 02:02
Is your model a `struct` or a `class`? Like I mentioned, it seems like you are passing the same imageView to each card and this could be why.

**Comment by timmyvc123** [comment] 2021-03-17 03:45
My model is a struct. I'm passing an imageView because based off my research it is a lot easier to download the image URL and display it in an imageView opposed to a UIImage. I'm going to try and configure it to a UIImage instead of imageView now

**Comment by mac-gallagher** [comment] 2021-03-17 03:52
@timmyvc123 Remember that an image view is actually a **view**, so it should not be part of the model

I would suggest instead having the image url in your card model and creating a constructor like `CardContentView:withImageUrl'

**Comment by timmyvc123** [comment] 2021-03-17 17:12
Thanks  @mac-gallagher! I don't think I would came up with this solution on my own.

I implemented this methid in `CardContentView` and the images are all in the right place now
```swift
    init(withImageURL imageURL: URL?) {
        super.init(frame: .zero)
        let getDataTask = URLSession.shared.dataTask(with: imageURL!) { (data, _, error) in
            guard let data = data, error == nil else {
                return
            }
            DispatchQueue.main.async {
                let coverImage = UIImage(data: data)
                self.imageView.image = coverImage
            }
        }
        getDataTask.resume()
        initialize()
    }
```

**Comment by timmyvc123** [comment] 2021-03-17 17:36
@mac-gallagher Just a quick question. In my project it plays the preview of whatever the current song is but I have come across a couple of issues doing this. I think the solution would be to make sure only the preview of the "top card" is playing. Do you have any advice on how to do this? As in just getting the top card and its values
