### ISSUE TITLE
Undo button doesn't display image

### ISSUE THREAD

**Issue by timmyvc123** [mac-gallagher/Shuffle#131] opened 2021-03-16 23:41 UTC
I've posted a similar issue on here which I had figured out before but it wasn't regarding the undo button. When I tap the undo button it just replaces current top card's image with previous card image. the top card should stay as is and when the undo button is tapped and the previous card is shown it should have it own correct image. When the undo button is pressed it shows the correct song title, artist name, and right preview of the song, just no the image. I've attached a video to better explain my issue.

My code is:

```Swift
     func cardStack(_ cardStack: SwipeCardStack, didUndoCardAt index: Int, from direction: SwipeDirection) {
       print("Undo \(direction) swipe on \(cardModels[index].songName)")
       var undoIndex = cardModels[index]
       undoIndex.imageView?.setImage(with: undoIndex.imageURL)
}
```

Before implementing this code it would still "undo" to the previous song correctly with right song title and artist name but the top card wouldn't change. Now it changes the top card image so I  feel like I'm getting closer to the solution.

https://user-images.githubusercontent.com/38578011/111393706-a57fe600-868f-11eb-8eb5-ed67f54b2035.mp4

**Comment by mac-gallagher** [comment] 2021-03-17 01:33
@timmyvc123  You should be setting the image in `cardForIndexAt`, not in `didUndoCardAt`.

Also, why is your image view part of the card model and not the card view? It looks like you may be using the same image view for each card, which is why you are only seeing one image at a time. Each content view should have it's own imageView This could be the source of your other issue

**Comment by mac-gallagher** [comment] 2021-03-17 01:44
Closing as this is a duplicate of #127. Added more comments there

**Closed by mac-gallagher** 2021-03-17 01:44 UTC
Labels: bug
